### ISSUE TITLE
The MoreLinq dependency is not included in the repository

### ISSUE THREAD

**Issue by Jared314** [M-Zuber/MyHome2013#56]
When the solution is opened on a new machine, the MoreLinq dependency is not found.

Switching to the [MoreLinq nuget package](http://www.nuget.org/packages/morelinq/1.1.0) might solve this issue for new developers.

**Comment by M-Zuber** [comment]
Actually, it should be removed. There should be a change in the development branch to that effect. I will check later today, and if yes,it will be merged into the main

**Comment by M-Zuber** [comment]
Closed with #59
